version: '3.8'
services:


  mysql:
    image: mysql:8.2
    volumes:
      - ./data:/var/lib/mysql
    build:
      context: .
      dockerfile: sql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: testdocker
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
 
 
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql

